language: cpp
dist: jammy
os: linux

compiler: gcc

addons:
  sonarcloud:
    organization: "sonarsource-cfamily-examples"
    token:
      secure: "ehFy4iiZfrrtsrSO3kMLBlXWzRocXYIj9dwx9GFKDH8wFScpe8N8syRh2D0ptMrXZkjQGYU9B6RSPO2PEa6hbYAljbcqTLOonDlujmrGKaUbDpeINyx/QCtcfN5lm5rdVECZ04U0xJgFTRNPb67WJrH9eSG6fEe/gmun8CzIasTvt6NfhPWW1ig5OvCoCFUUWgSqG7irATvRaVZeaBcKambvzeCrNI7WnI+AdkUa9kjlW7+Qf57qChICnPLS1CubyfjvMjLogU9n4f8H/YHyKyrzBicaCeOI3YydI6fFr9XeF7DjPXyJXZeyNzoObbiFC+epk8yqtBmTT6aN0BNS777u97r4szDlmzcQA/SkQsyITOsUjVT6FYsq9wAFOXfxxoQ3Nltp68KuJl96G9LGpHKjVyYrfFTQvL2r+Q0vJ/eCbOJ/rI0/fzwgWtII+Jn0IPV8GdJZf+uFOvYGw80EqK5mUmPORYnt+pf87/kZ6Y3TcmMNr/xv7TjOhMhFnbVg/TB25HEi/QnjTroTs1AELbWlzqC5T/IPA1hjAd7h8bfOyzOpD5MUWJiE+pNEIe5C5sxJ13IVQpgh03tFgUzgksT6niwwP1OnhiwVQ+v3pH7LZ7M6HRc9QS2RPZGDJDYYcGAa3XiHyQz71U2BgrOpRzMkTly3jju48Ph4dxSq1LI="
  apt:
    packages:
      - g++-9
      - cmake
      - openjdk-17-jre

env:
  - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 PATH=$JAVA_HOME/bin:$PATH CXX=g++-9 BUILD_WRAPPER_OUT_DIR=build_wrapper_output_directory

script:
  # Prepare the build system
  - autoreconf --install
  - ./configure
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "build_wrapper_output_directory" folder
  - build-wrapper-linux-x86-64 --out-dir "$BUILD_WRAPPER_OUT_DIR" make clean all
  # Execute the tests to generate the coverage statistics
  - ./src/test1/coverage_test1
  - ./src/test2/coverage_test2
  # Run gcov to translate `.gcda` files into `.gcov` readable by humans and SonarCloud
  - mkdir coverage-dir
  - cd coverage-dir
  # --preserve-paths helps us avoid name clash for `.gcov` files corresponding to source files
  # with the same name but in different directories.
  - find .. -name '*.o' | xargs gcov --preserve-paths
  - cd ..
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner --define sonar.cfamily.gcov.reportsPath="coverage-dir"

cache:
  directories:
    - $HOME/.sonar/cache
