language: cpp
dist: jammy
os: linux

compiler: gcc

addons:
  sonarcloud:
    organization: "sonarsource-cfamily-examples"
    token:
      secure: "Bacg7ERHYC6ouUa5+MwNjj+pHslPBMbJNrzYFDOC0poYijOFWWKPvVXHBFJAcbHMsy2WiO+F0H6Nsch2Eq7PY9EYc11RkMkdO3qs3711kzgnUgfmuxwz4EBIWjosZa2fGa8jCNkG6OD7/LSxMMe/lnibDJDLCVM4RwIbQ5LrIHJoqqAFDjTPfx5fv7gUt+IQ4t8/Q/uqWEq0I1pNs7itSpTyikCNzeXlmrOOvjM+hwsM8PIeiLPKAEpA2CfkD6B8bE/yHpJ2WBVECtbj87+5NdhGD28rj25cs+/UHk6cvhn9nllmOfQX+XDXFlCp2NXETswO3q5XP5nwlochfFkEmIvx5+7mq+74/S5Hpq1MJZCk6fcA5/tLOV2q98WbgESb8EiczaPkmaeW82OFVKZsWLx+NMl9cOPJW9xkFCyB4mZjcLJ1wtiw9Bc6ld/GQrzmA42ia1IIIQMRTxLgxeqe/t9NrgP8X+moVlJ1oDcv8fEPu9bGBWaxeHzHwWodZwluaxx1GQr0wHbgxaaAf+hvX+iJsfA69qhh3riowuRpfGrumLtl7zEXD5xc3CYlU3hmQG+zChV0ZDqa/2o1Zoopr+DAa7PnKbxJAwanLNnARDa85hwrPVal9o2EsGIpXuw5gA/FSHZRLoYFdV4gENykFctgQwsJ/HqmM7FOFHuLPx0="
  apt:
    packages:
      - g++-9
      - cmake
      - openjdk-17-jre

env:
  - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 PATH=$JAVA_HOME/bin:$PATH CXX=g++-9 BUILD_WRAPPER_OUT_DIR=build_wrapper_output_directory

script:
  # Prepare the build system
  - autoreconf --install
  - ./configure
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "build_wrapper_output_directory" folder
  - build-wrapper-linux-x86-64 --out-dir "$BUILD_WRAPPER_OUT_DIR" make clean all
  # Execute the tests to generate the coverage statistics
  - ./src/test1/coverage_test1
  - ./src/test2/coverage_test2
  # Run gcov to translate `.gcda` files into `.gcov` readable by humans and SonarCloud
  - mkdir coverage-dir
  - cd coverage-dir
  # --preserve-paths helps us avoid name clash for `.gcov` files corresponding to source files
  # with the same name but in different directories.
  - find .. -name '*.o' | xargs gcov --preserve-paths
  - cd ..
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner --define sonar.cfamily.gcov.reportsPath="coverage-dir"

cache:
  directories:
    - $HOME/.sonar/cache
