= C++ example project scanned on SonarCloud using Travis CI, with test coverage generated by gcov
// URIs:
:uri-qg-status: https://sonarcloud.io/dashboard?id=sonarsource-cfamily-examples_linux-autotools-gcov-travis-sc
:img-qg-status: https://sonarcloud.io/api/project_badges/measure?project=sonarsource-cfamily-examples_linux-autotools-gcov-travis-sc&metric=alert_status
:uri-build-status: https://app.travis-ci.com/sonarsource-cfamily-examples/linux-autotools-gcov-travis-sc
:img-build-status: https://app.travis-ci.com/sonarsource-cfamily-examples/linux-autotools-gcov-travis-sc.svg?branch=main

image:{img-build-status}[Build Status, link={uri-build-status}]
image:{img-qg-status}[Quality Gate Status,link={uri-qg-status}]

*This project is analysed on https://sonarcloud.io/dashboard?id=sonarsource-cfamily-examples_linux-autotools-gcov-travis-sc[SonarCloud]!*

:note-caption: :information_source:
NOTE: This simple example ignores https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache[analysis cache] and https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#parallel-code-scan[multithreaded execution] both of which can boost analysis significantly.

It is very easy to analyze a C, C++ and Objective-C project with SonarCloud https://docs.travis-ci.com/user/sonarcloud/[on Travis CI]:

. Create a `sonar-project.properties` file to store your configuration
. In your `.travis.yml` file:
.. Activate the https://docs.travis-ci.com/user/sonarcloud/[Travis Add-on] and add it to your `.travis.yml` file:
* Specify your GitHub `organization`
* add your encrypted `SONAR_TOKEN`
.. Wrap your compilation with the https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-steps-using-build-wrapper[Build Wrapper]
* Add the `--coverage` and `-fprofile-abs-path` compilation flags to instrument the binaries
.. Run the tests to generate the test coverage information
.. Run `gcov --preserve-paths` from a dedicated directory for each object file
.. Run `sonar-scanner` later on, with `sonar.cfamily.gcov.reportsPath` pointing at that dedicated directory with coverage reports

Note: `SONAR_TOKEN` may be also configured as enviroment variable in Repository Settings of Travis CI.

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:.travis.yml[.travis.yml] to see it in practice.

== This project uses gcov to collect test coverage
For SonarCloud to pick-up the coverage information produced from compiling with the `--coverage` flag and running the tests,
you need to run gcov for each object file
and point `sonar.cfamily.gcov.reportsPath` property to the folder containing the produced `.gcov` files.

:warning-caption: :warning:
WARNING: Beware that if you are running multiple executables and want to collect coverage from all of them, you have to be careful of keeping one `.gcda` file per source file and avoid overwriting `.gcov` files (especially if you are building out-of-source, for example, with CMake). See also `-fprofile-abs-path` gcc option and `--preserve-paths` gcov option.


= Documentation

- https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/[Documentation of the C, C++ and Objective-C plugin and its Build Wrapper]
- https://docs.travis-ci.com/user/sonarcloud/[Documentation of the SonarCloud Travis Add-on]
- https://docs.sonarcloud.io/getting-started/github/[Documentation of using SonarCloud with GitHub]
- https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache[Configuring C, C++ and Objective-C analysis cache]
- https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#parallel-code-scan[Configuring multithreaded execution]
- https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-steps-using-compilation-database[Using compilation database (compile_commands.json)]

= Linux\Autotools

A build of the https://github.com/sonarsource-cfamily-examples/code[code repository] on a Linux platform using GNU Autotools build system.

To build the code run:
----
autoreconf --install
./configure
make clean all
----

= Code Description

An example of a flawed C++ code. The https://github.com/sonarsource-cfamily-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sonarsource-cfamily-examples/code[code repository] is forked into other repositories in https://github.com/sonarsource-cfamily-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sonarsource-cfamily-examples?q=linux[Linux]
* https://github.com/sonarsource-cfamily-examples?q=macos[MacOS]
* https://github.com/sonarsource-cfamily-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sonarsource-cfamily-examples?q=cmake[CMake]
* https://github.com/sonarsource-cfamily-examples?q=autotools[GNU Autotools]
* https://github.com/sonarsource-cfamily-examples?q=xcode[Xcode]
* https://github.com/sonarsource-cfamily-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sonarsource-cfamily-examples?q=azure[Azure DevOps]
* https://github.com/sonarsource-cfamily-examples?q=gh-actions[GitHub Actions]
* https://github.com/sonarsource-cfamily-examples?q=travis[Travis]
* https://github.com/sonarsource-cfamily-examples?q=jenkins[Jenkins]
* https://github.com/sonarsource-cfamily-examples?q=gitlab[GitLab CI]
* https://github.com/sonarsource-cfamily-examples?q=bitbucket[BitBucket Pipelines]
* Additionally, https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=otherci[generic examples] demonstrate integration with other CIs and https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=manual[manual-configuration examples] should help you if you are running locally.

Configured for analysis on:

* https://github.com/sonarsource-cfamily-examples?q=-sq[SonarQube]
* https://github.com/sonarsource-cfamily-examples?q=-sc[SonarCloud]

You can find also a few examples demonstrating:

* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=compdb[The use of Compilation Database (compile_commands.json)]
* https://github.com/orgs/sonarsource-cfamily-examples/repositories?q=topic%3Acoverage[Test coverage]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sonarsource-cfamily-examples[this GitHub organization] and the relations between its different repositories.
